-- ============================================================================
-- 🏭 食品加工厂 ERP 系统 - 数据库初始化脚本
-- 在 Supabase SQL Editor 中执行此脚本
-- ============================================================================

-- 1. 用户表 (扩展 Supabase Auth)
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    role TEXT DEFAULT 'employee', -- admin, employee
    created_at TIMESTAMP DEFAULT NOW()
);

-- 2. 商品表
CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    base_unit TEXT DEFAULT '斤',
    display_unit TEXT DEFAULT '罐',
    conversion_rate NUMERIC DEFAULT 0.5,
    price_tier_1 NUMERIC DEFAULT 0, -- 大客户价
    price_tier_2 NUMERIC DEFAULT 0, -- 常规价
    price_tier_3 NUMERIC DEFAULT 0, -- 零散价
    current_stock NUMERIC DEFAULT 0,
    created_at TIMESTAMP DEFAULT NOW()
);

-- 3. 库存流水表
CREATE TABLE IF NOT EXISTS inventory_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES products(id),
    type TEXT NOT NULL, -- IN, OUT_SALE, OUT_GIFT, OUT_INTERNAL, LOSS, RETURN_GOOD, RETURN_BAD
    quantity NUMERIC NOT NULL,
    date DATE DEFAULT CURRENT_DATE,
    remark TEXT,
    created_at TIMESTAMP DEFAULT NOW()
);

-- 4. 客户表
CREATE TABLE IF NOT EXISTS customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    phone TEXT,
    address TEXT,
    price_level INT DEFAULT 2, -- 1:大客户，2:常规，3:零散
    latitude NUMERIC,
    longitude NUMERIC,
    created_at TIMESTAMP DEFAULT NOW()
);

-- 5. 订单主表
CREATE TABLE IF NOT EXISTS orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT REFERENCES customers(id),
    order_date DATE DEFAULT CURRENT_DATE,
    total_amount NUMERIC DEFAULT 0,
    paid_amount NUMERIC DEFAULT 0,
    payment_method TEXT, -- 微信，支付宝，现金，赊账
    driver_expense NUMERIC DEFAULT 0,
    status TEXT DEFAULT 'pending', -- pending, shipped, delivered
    is_printed BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT NOW()
);

-- 6. 订单明细表
CREATE TABLE IF NOT EXISTS order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT REFERENCES orders(id),
    product_id BIGINT REFERENCES products(id),
    quantity NUMERIC NOT NULL,
    unit_price NUMERIC NOT NULL,
    is_free_gift BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT NOW()
);

-- 7. 原材料表
CREATE TABLE IF NOT EXISTS materials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    current_price NUMERIC DEFAULT 0,
    stock_quantity NUMERIC DEFAULT 0,
    unit TEXT DEFAULT '斤',
    created_at TIMESTAMP DEFAULT NOW()
);

-- 8. 材料价格表 (爬虫数据)
CREATE TABLE IF NOT EXISTS material_prices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    material_name TEXT NOT NULL,
    price NUMERIC NOT NULL,
    region TEXT,
    price_change TEXT,
    date DATE DEFAULT CURRENT_DATE,
    source TEXT,
    crawl_time TIMESTAMP DEFAULT NOW()
);

-- 9. 政策新闻表 (爬虫数据)
CREATE TABLE IF NOT EXISTS policy_news (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    source TEXT,
    region TEXT,
    summary TEXT,
    url TEXT,
    publish_date DATE,
    crawl_time TIMESTAMP DEFAULT NOW()
);

-- 10. 潮汕企业表
CREATE TABLE IF NOT EXISTS chaoshan_companies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    industry TEXT,
    phone TEXT,
    address TEXT,
    contact TEXT,
    created_at TIMESTAMP DEFAULT NOW()
);

-- 11. 员工表
CREATE TABLE IF NOT EXISTS employees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    phone TEXT,
    position TEXT,
    base_salary NUMERIC DEFAULT 0,
    hire_date DATE,
    status TEXT DEFAULT 'active',
    created_at TIMESTAMP DEFAULT NOW()
);

-- 12. 工资表
CREATE TABLE IF NOT EXISTS salaries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT REFERENCES employees(id),
    year INT,
    month INT,
    basic_salary NUMERIC DEFAULT 0,
    bonus NUMERIC DEFAULT 0,
    overtime NUMERIC DEFAULT 0,
    social_insurance NUMERIC DEFAULT 0,
    tax NUMERIC DEFAULT 0,
    total_paid NUMERIC DEFAULT 0,
    created_at TIMESTAMP DEFAULT NOW()
);

-- 13. 支出表
CREATE TABLE IF NOT EXISTS expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type TEXT NOT NULL, -- driver_expense, material, salary, other
    amount NUMERIC NOT NULL,
    date DATE DEFAULT CURRENT_DATE,
    remark TEXT,
    created_at TIMESTAMP DEFAULT NOW()
);

-- ============================================================================
-- 初始化数据
-- ============================================================================

-- 插入默认管理员 (密码需要在 Supabase Auth 中创建)
INSERT INTO users (email, role) VALUES ('admin@factory.com', 'admin')
ON CONFLICT (email) DO NOTHING;

-- 插入示例商品
INSERT INTO products (name, base_unit, display_unit, conversion_rate, price_tier_1, price_tier_2, price_tier_3, current_stock) VALUES
('香脆花生', '斤', '罐', 0.5, 15, 18, 22, 100),
('花生酥糖', '斤', '包', 0.25, 20, 25, 30, 50),
('花生油', '斤', '瓶', 1, 25, 30, 35, 80)
ON CONFLICT DO NOTHING;

-- 插入示例客户
INSERT INTO customers (name, phone, address, price_level) VALUES
('张三超市', '13800138000', '汕头市 XX 路', 1),
('李四便利店', '13900139000', '揭阳市 XX 街', 2),
('王五小卖部', '13700137000', '潮州市 XX 巷', 3)
ON CONFLICT DO NOTHING;

-- 插入示例原材料
INSERT INTO materials (name, current_price, stock_quantity, unit) VALUES
('花生仁', 6.5, 500, '斤'),
('白糖', 5.8, 200, '斤'),
('花生油', 12.5, 100, '斤'),
('白萝卜', 2.3, 300, '斤'),
('姜', 8.5, 50, '斤')
ON CONFLICT DO NOTHING;

-- ============================================================================
-- 创建索引 (优化查询性能)
-- ============================================================================

CREATE INDEX IF NOT EXISTS idx_inventory_logs_date ON inventory_logs(date);
CREATE INDEX IF NOT EXISTS idx_orders_date ON orders(order_date);
CREATE INDEX IF NOT EXISTS idx_orders_customer ON orders(customer_id);
CREATE INDEX IF NOT EXISTS idx_material_prices_date ON material_prices(date);

-- ============================================================================
-- 创建视图 (方便查询)
-- ============================================================================

-- 客户欠款视图
CREATE OR REPLACE VIEW customer_debt AS
SELECT 
    c.id,
    c.name,
    SUM(o.total_amount - o.paid_amount) as total_debt
FROM customers c
JOIN orders o ON c.id = o.customer_id
WHERE o.total_amount > o.paid_amount
GROUP BY c.id, c.name;

-- 库存预警视图 (库存低于 10 的商品)
CREATE OR REPLACE VIEW low_stock_alert AS
SELECT * FROM products WHERE current_stock < 10;

-- ============================================================================
-- 完成提示
-- ============================================================================
-- ✅ 数据库初始化完成！
-- 请在 Supabase Auth 中创建 admin@factory.com 用户，密码：admin123